image:
  name: hashicorp/terraform:light
  entrypoint: [""]

stages:
  - test
  - init
  - plan
  - apply

test:
  stage: test
  script:
    - terraform --version
    - cd environments/dev

init:
  stage: init
  script: terraform init

plan:
  stage: plan
  script: terraform plan

apply:
  stage: apply
  script: terraform apply

