image:
  name: hashicorp/terraform:light
  entrypoint: [""]

before_script:
  - rm -rf .terraform
  - terraform --version
  - echo $(pwd)
  - terraform init

stages:
  - plan

plan:
  stage: plan
  script:
    - terraform init
