image:
  name: hashicorp/terraform:light
  entrypoint: [""]

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - terraform --version
    - export TF_LOG=TRACE
    - cd environments/dev
    - terraform init
    - terraform plan

deploy_dev:
  stage: deploy
  script:
    - terraform --version
    - export TF_LOG=TRACE
    - cd environments/dev
    - terraform init
    - terraform plan
    - terraform apply

